name: Audioreach Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Repo-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t audioreach-build .
          
      - name: Create output directory
        run: mkdir -p ./output

      - name: Run Docker container
        run: docker run --name audioreach audioreach-build

      - name: Copy artifacts from container
        run: docker cp audioreach:/app/output ./output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./output

